name: Deploy Positive Life on Github Pages
run-name: ${{ github.actor }} is deploying Positive Life on Github Pages 🚀
on: [push]
jobs:
  build:
    name: Build App with trunk
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: 'latest'
      - name: Build
        run: trunk build
      - name: List files built
        run: |
          ls ${{ github.workspace }}/dist
  deploy:
    name: Deploy App on Github pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Deploying"
