name: Deploy Positive Life on Github Pages
run-name: ${{ github.actor }} is deploying Positive Life on Github Pages 🚀
on: [push]

jobs:
  # Build job
  build:
    name: Build App with trunk 📦
    runs-on: ubuntu-latest

    steps:
      #Checkout files
      - name: Check out repository code
        uses: actions/checkout@v3

      # Install Rust env
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      # Build
      - name: Build
        run: trunk build --public-url ${{ github.repository }}
      - name: List files built
        run: ls ${{ github.workspace }}/dist

      # Upload pages
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/dist/

  # Deploy job
  deploy:
    name: Deploy App on Github pages 🚀
    needs: build
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Deploy pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
