name: Deploy Positive Life on Github Pages
run-name: ${{ github.actor }} is deploying Positive Life on Github Pages 🚀
on: [push]
jobs:
  build:
    name: Build App with trunk 📦
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: 'latest'
      - name: Build
        run: trunk build
      - name: List files built
        run: ls ${{ github.workspace }}/dist
      - name: Upload built files
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/dist/
  deploy:
    name: Deploy App on Github pages 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}
      - name: Display list of deployed files
        run: ls -R
        working-directory: ${{ github.workspace }}
